sonar.projectKey=Olimpia-pub
sonar.projectName=Olimpia-pub
sonar.projectVersion=1.0
sonar.projectBaseDir=Olimpia-pub

sonar.sources=app,routes,resources
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,app/Models/User.php,resources/css/app.css
sonar.coverage.exclusions=app/Models/User.php,resources/**
sonar.php.coverage.reportPaths=storage/coverage/clover.xml
sonar.host.url=http://localhost:9000
