sonar.projectKey=Olimpia-pub
sonar.projectName=Olimpia-pub
sonar.projectVersion=1.0
sonar.projectBaseDir=Olimpia-pub

sonar.sources=app,routes,resources
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/cache/**,app/Models/User.php,resources/css/app.css,**/.sonar-token,.sonar-token
sonar.coverage.exclusions=app/Models/User.php,resources/**
sonar.php.coverage.reportPaths=storage/coverage/coverage.xml
sonar.php.tests.reportPath=storage/coverage/junit.xml
sonar.host.url=http://localhost:9000
