sonar.projectKey=Olimpia-pub
sonar.projectName=Olimpia-pub
sonar.projectVersion=1.0

# Carpetas de Laravel que queremos analizar (sin incluir librerías externas)
sonar.sources=app, config, database, routes, resources
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Ignorar carpetas pesadas o autogeneradas para que no alienten el escaneo
sonar.exclusions=vendor/**, node_modules/**, public/**, storage/**
